### ISSUE TITLE
missing capability checks

### ISSUE THREAD

**Issue by danmarsden** [edumeet/moodle-mod_edumeet#2]
All pages should implement appropriate capability checks - I can see you have added require_course_login, but this is not enough. see here for a summary of our security guidelines:
https://docs.moodle.org/dev/Security#Summary_of_the_guidelines

ideally you should implement a mod/multipartymeeting:view capability -and check that before displaying a meeting or a link to the meeting etc.

**Comment by N7Remus** [comment]
@danmarsden Added mod/multipartymeeting:view capability
