### ISSUE TITLE
invalid install.xml

### ISSUE THREAD

**Issue by danmarsden** [edumeet/moodle-mod_edumeet#3]
your install.xml file looks incorrect and may cause issues for some sites.

You need to use the built-in xmldb editor UI in Moodle to fix this - easiest way to do this is to open it in the xmldb editor and make a change to a comment on a field or table to trigger a change - then use the xmldb editor built-in functions to save the file (you may need to change file-level permissions to allow xmldb editor to save the file.)

**Comment by N7Remus** [comment]
@danmarsden Fixed
