### ISSUE TITLE
incorrectly defined settings.

### ISSUE THREAD

**Issue by danmarsden** [edumeet/moodle-mod_edumeet#7]
https://github.com/misi/moodle-mod_multipartymeeting/blob/master/settings.php#L31
settings like "multipartymeeting_baseurl" should be defined as "multipartymeeting/baseurl" - this puts them in the correct location within the config_plugins table - you should not be using the global $CFG variable but using the get_config('multipartymeeting') function to obtain settings within the correct location.

more information on this is available here:
https://docs.moodle.org/dev/Admin_settings

**Comment by misi** [comment]
@danmarsden  I will try to fix all! 
Many thanks for the review!

**Comment by danmarsden** [comment]
no worries! - will be great to see a multipartymeeting plugin in the plugins db! :-)

**Comment by N7Remus** [comment]
@danmarsden fixed
